export const tokens = {
  canvas: 'var(--canvas)',
  canvasDeep: 'var(--canvas-deep)',
  panel: 'var(--panel)',
  panelLift: 'var(--panel-lift)',
  hairline: 'var(--hairline)',
  hairlineStrong: 'var(--hairline-strong)',
  hairlineFaint: 'var(--hairline-faint)',
  ink: 'var(--ink)',
  ink2: 'var(--ink-2)',
  ink3: 'var(--ink-3)',
  ink4: 'var(--ink-4)',
  terracotta: 'var(--terracotta)',
  terracottaSoft: 'var(--terracotta-soft)',
  gold: 'var(--gold)',
  amber: 'var(--amber)',
  amberBg: 'var(--amber-bg)',
  amberBorder: 'var(--amber-border)',
  amberInk: 'var(--amber-ink)',
  green: 'var(--green)',
  greenBg: 'var(--green-bg)',
  greenBorder: 'var(--green-border)',
  greenInk: 'var(--green-ink)',
  clay: 'var(--clay)',
  clayBg: 'var(--clay-bg)',
  clayBorder: 'var(--clay-border)',
  clayInk: 'var(--clay-ink)',
  neutralBg: 'var(--neutral-bg)',
  neutralBorder: 'var(--neutral-border)',
  neutralInk: 'var(--neutral-ink)',
  dark: 'var(--dark)',
  darkLift: 'var(--dark-lift)',
  darkLine: 'var(--dark-line)',
  darkLineStrong: 'var(--dark-line-strong)',
  darkText: 'var(--dark-text)',
  darkText2: 'var(--dark-text-2)',
  darkText3: 'var(--dark-text-3)',
  darkTerracotta: 'var(--dark-terracotta)',
} as const;

export type TodayToken = keyof typeof tokens;
